# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: SynopsysSecurityScan@1.0.0
  displayName: 'Polaris Scan'
  inputs:
    scanType: polaris
    bridge_polaris_serverUrl: $(BRIDGE_POLARIS_SERVERURL)
    bridge_polaris_accessToken: $(BRIDGE_POLARIS_ACCESSTOKEN)
    bridge_polaris_application_name: $(BRIDGE_POLARIS_APPLICATION_NAME)
    bridge_polaris_project_name: $(BRIDGE_POLARIS_PROJECT_NAME)
    bridge_polaris_assessment_types: "SCA,SAST"
