
Skip to content
Navigation Menu

    SRH-Test

    hello-java

Code
Pull requests
Actions
Projects
Wiki
Security
Insights

    Settings

Don't get locked out of your account. Download your recovery codes or add a passkey so you don't lose access when you get a new device.
Polaris-Scan
Update polaris.yml #6

Jobs

Run details

Workflow file for this run
.github/workflows/polaris.yml at 798848a
# example workflow for SRM scans using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
name: Polaris-Scan
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Polaris Scan
      uses: blackduck-inc/black-duck-security-scan@v2.0.0
      with:
        polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESSTOKEN }}
        polaris_assessment_types: 'SAST,SCA'
        polaris_application_name: SRH-${{ github.event.repository.name }}
        polaris_prComment_enabled: 'true'
        polaris_reports_sarif_create: 'true'
        polaris_upload_sarif_report: 'true'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # include_diagnostics: true
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
Update polaris.yml · SRH-Test/hello-java@798848a

